<?php

namespace App\Http\Livewire;

use App\Course;
use App\Program;
use Illuminate\Support\Facades\Auth;
use Mediconesystems\LivewireDatatables\BooleanColumn;
use Mediconesystems\LivewireDatatables\Column;
use Mediconesystems\LivewireDatatables\Http\Livewire\LivewireDatatable;
use Mediconesystems\LivewireDatatables\NumberColumn;

class CourseTable extends LivewireDatatable
{
    public $model       = Course::class;
    public $hideable    = 'select';
    public $exportable  = true;

    protected $listeners = ['refreshLivewireDatatable'];

    public function builder()
    {

       //TODO Datos según departamento
       return $this->model::query(); // TODO: Change the autogenerated stub
    }

    public function columns()
    {
        return [
           NumberColumn::callback(['id'], function ($id){
              return $id;
           })->label('id'),
           Column::name('code')->label('Código')->filterable()->searchable(),
           Column::name('name')->label('Nombre Materia')->editable()->filterable()->searchable(),
           BooleanColumn::name('state')->label('Estado')->filterable()->hide(),
           Column::name('program.name')->filterable(
              $this->programs->pluck('name')
           )->label('Programa'),
           Column::name('id')->view('livewire.datatables.edit')->label('Editar')->alignRight()->hide(),
           Column::delete()->label('Eliminar')->alignRight()->hide()
        ];
    }

    public function getProgramsProperty()
    {
       return Program::all('name');
    }

    public function edit($id)
    {
      $this->emit('edit', $id);
    }
}