<?php


namespace App\Http\Livewire;


use App\Department;
use Illuminate\Database\QueryException;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Maatwebsite\Excel\Facades\Excel;
use Mediconesystems\LivewireDatatables\BooleanColumn;
use Mediconesystems\LivewireDatatables\Column;
use Mediconesystems\LivewireDatatables\DateColumn;
use Mediconesystems\LivewireDatatables\Exports\DatatableExport;
use Mediconesystems\LivewireDatatables\Http\Livewire\LivewireDatatable;
use Mediconesystems\LivewireDatatables\NumberColumn;

class DepartmentTable extends LivewireDatatable
{
   public $model = Department::class;
   public $hideable = 'select';
   public $exportable = true;

   protected $listeners = ['refreshLivewireDatatable'];


   //TODO crear builder de los datos de la tabla

   public function columns() : array
   {
      $columns = [
         NumberColumn::callback(['id'], function ($id){
            return $id;
         })->label('id'),
         Column::name('name')->label('Nombre')->searchable()->truncate(),
         BooleanColumn::name('state')->label('Estado')->filterable(),
         DateColumn::name('created_at')->label('Fecha creación')->filterable(),
      ];
      if (Auth::user()->can('category_write')) {
         array_push($columns, Column::name('id')->view('livewire.datatables.edit')->label('Editar')->alignRight());
      }
      if (Auth::user()->can('category_destroy')){
         array_push($columns, Column::delete()->label('Eliminar')->alignRight()->hide());
      }

      return $columns;
   }

   public function refreshLivewireDatatable()
   {
      parent::refreshLivewireDatatable(); // TODO: Change the autogenerated stub
   }

   public function export()
   {
      $export = collect();
      $this->forgetComputed();
      foreach ($this->getQuery()->get() as $item) {
         $export->push([
            'Nombre' => $item->name,
            'Estado' => $item->state == 1 ? 'Activo' : 'Desactivado',
         ]);
      }
      return Excel::download(new DatatableExport($export), 'DatatableExport.xlsx');
   }

   public function edit($id)
   {
      $this->emit('edit', $id);
   }
}