<?php


namespace App\Http\Livewire;


use Mediconesystems\LivewireDatatables\Column;
use Mediconesystems\LivewireDatatables\Http\Livewire\LivewireDatatable;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class PermissionTable extends LivewireDatatable
{
   public $model = Permission::class;

   public $search = false, $role_id = null;

   public $title = "Asignar Permiso";
   protected $listeners = ['refreshLivewireDatatable', 'refreshTableCustom'];

   public $afterTableSlot = 'livewire.permission-rol.select';

   public function builder()
   {

      if (!is_null($this->role_id) and !empty($this->role_id)) {
         $this->selected = [];
         foreach (Role::findById($this->role_id)->permissions->toArray() as $permission) {
            array_push($this->selected, $permission['name']);
         }
         $this->role_id = null;
      }
      return $this->model::query();
   }

   public function columns()
   {
      return [
         Column::name('name')->filterable()->label('Rol'),
         Column::checkbox('name')->label('Asignar'),
         Column::name('id')->view('livewire.datatables.edit')->label('Editar')->alignRight(),
      ];
   }

   public function assign()
   {
      $this->emit('assign', $this->selected);
   }

   public function edit($id)
   {
      $this->emit('edit', $id);
   }

   public function refreshTableCustom($role_id)
   {
      $this->role_id = $role_id;
      parent::refreshLivewireDatatable(); // TODO: Change the autogenerated stub
   }
}