<?php


namespace App\Http\Livewire;


use App\Department;
use App\Program;
use App\Traits\LogsTrail;
use App\Traits\SetParamsTable;
use Mediconesystems\LivewireDatatables\BooleanColumn;
use Mediconesystems\LivewireDatatables\Column;
use Mediconesystems\LivewireDatatables\Http\Livewire\LivewireDatatable;
use Mediconesystems\LivewireDatatables\NumberColumn;

/**
 * Libreria https://github.com/mediconesystems/livewire-datatables
 * Class ProgramSearchTable
 * @package App\Http\Livewire
 *
 */
class ProgramSearchTable extends LivewireDatatable
{
   use SetParamsTable, LogsTrail;

   public $model        = Program::class;

   public $exportable   = true;

   protected $listeners = ['setNewDate'];

   public $hideable    = 'select';

   public function builder()
   {
      return $this->model::query()
         ->where('name', 'like', "%$this->params%")
         ->orWhere('faculty', 'like', "%$this->params%")
         ->orWhere('code', 'like', "%$this->params%");
   }

   public function columns() : array
   {
      $columns = [
         Column::name('name')->label(__('modules.program.name'))->filterable()->searchable(),
         Column::name('code')->label(__('modules.input.code'))->filterable()->searchable(),
         Column::name('faculty')->label(__('modules.input.faculty'))->filterable()->searchable(),
         BooleanColumn::name('state')->label(__('modules.input.state'))->filterable(),
         NumberColumn::name('courses.id:count')->label('# de Asignaturas')->filterable()->alignCenter(),
         Column::callback(['id'], function ($id){
            return view('fragments.link-to', ['route' => 'program-detail', 'params' => ['id' => $id], 'name' => 'Ver', 'btn' => 'btn-blue']);
         })->label(__('modules.table.detail'))->alignRight()->excludeFromExport(),
      ];
      return $columns;
   }

   public function getDepartmentProperty()
   {
      return Department::all('name');
   }

   public function render()
   {
      $this->emit('stopClear');
      $this->setLog('info', 'Búsqueda programa', 'render', __('modules.search.title'));
      return parent::render(); // TODO: Change the autogenerated stub
   }
}
