<?php

namespace App\Http\Livewire;

use App\Student;
use Illuminate\Support\Facades\Auth;
use Mediconesystems\LivewireDatatables\BooleanColumn;
use Mediconesystems\LivewireDatatables\Column;
use Mediconesystems\LivewireDatatables\DateColumn;
use Mediconesystems\LivewireDatatables\Http\Livewire\LivewireDatatable;
use Mediconesystems\LivewireDatatables\NumberColumn;

class StudentTable extends LivewireDatatable
{

    public $model = Student::class;

    public $hideable = 'select';

    public $exportable = true;

   protected $listeners = ['refreshLivewireDatatable'];

   public function builder()
    {
        return $this->model::query();
    }

    public function columns()
    {
        $columns = [
            Column::name('name')->label('Nombres')->editable()->filterable()->searchable(),
            Column::name('last_name')->label('Apellidos')->filterable()->searchable()->editable(),
            Column::name('email')->label('Email')->filterable()->searchable(),
            Column::name('document')->label('Documento')->filterable()->searchable(),
            BooleanColumn::name('state')->label('Estado')->filterable()->hide(),
            DateColumn::name('created_at')->label('Fecha creación')->filterable(),
            Column::callback(['id'], function ($id){
               return view('fragments.link-to', ['route' => 'student-detail', 'params' => ['id' => $id], 'name' => 'Ver']);
            })->label('Detalle'),
        ];
        if (Auth::user()->can('moodle_write')) {
           array_push($columns, Column::name('id')->view('livewire.datatables.edit')->label('Editar')->alignRight());
        }
        if (Auth::user()->can('moodle_destroy')){
          array_push($columns, Column::delete()->label('Eliminar')->alignRight()->hide());
        }

        return $columns;
    }

    public function refreshLivewireDatatable()
    {
       parent::refreshLivewireDatatable(); // TODO: Change the autogenerated stub
    }

    public function edit($id)
    {
       $this->emit('edit', $id);
    }

}