<?php
namespace App\Http\Livewire;

use App\Student;
use App\Traits\DeleteMassive;
use App\User;
use Illuminate\Database\QueryException;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Mediconesystems\LivewireDatatables\BooleanColumn;
use Mediconesystems\LivewireDatatables\Column;
use Mediconesystems\LivewireDatatables\DateColumn;
use Mediconesystems\LivewireDatatables\Http\Livewire\LivewireDatatable;

class UserTable extends LivewireDatatable
{

   use DeleteMassive;

   public $model        = User::class;

   public $hideable     = 'select';

   public $exportable   = true;

   public $beforeTableSlot = 'fragments.delete-massive';

   protected $listeners = ['refreshLivewireDatatable'];

   public $relation     = 'user';

   public function builder()
   {
      //TODO Datos según departamento
      //return $this->model::query()->where('users.department_id', Auth::user()->department_id); // TODO: Change the autogenerated stub
      return $this->model::query();
   }

   public function columns() : array
   {
      $relation = $this->relation;
      $columns = [
         Column::checkbox('id'),
         Column::name('name')->label('Nombres')->filterable()->searchable()->editable(),
         Column::name('last_name')->label('Apellidos')->filterable()->searchable()->editable(),
         Column::name('document')->label('Documento')->filterable()->searchable(),
         Column::name('username')->label('Email')->filterable()->searchable(),
         BooleanColumn::name('state')->label('Estado')->filterable()->hide(),
         Column::name('department.name')->filterable()->label('Categoria'),
         DateColumn::name('created_at')->label('Fecha creación')->filterable(),
         Column::callback(['id', 'name'], function ($id){
            return view('fragments.btn-action-reset-password', ['action' => 'reset', 'value' => $id, 'name' => 'Reiniciar']);
         })->label('Reiniciar Contraseña')->alignCenter(),
      ];
      if (Auth::user()->can('user_detail')) {
         array_push($columns,  Column::callback(['id'], function ($id){
            return view('fragments.link-to', ['route' => 'user-detail', 'params' => ['id' => $id]]);
         })->label('Detalle')->alignCenter());
      }
      if (Auth::user()->can('user_write')) {
         array_push($columns, Column::name('id')->view('livewire.datatables.edit')->label('Editar')->alignCenter());
      }
      if (Auth::user()->can('user_destroy')){
         array_push($columns, Column::callback(['id', 'document'], function ($id) use ($relation){
            return view('fragments.btn-action-delete', [
               'value' => $id, 'relation' => $relation
            ]);
         })->label('Eliminar')->alignCenter()->hide());
      }

      return $columns;
   }

   public function refreshLivewireDatatable()
   {
      parent::refreshLivewireDatatable(); // TODO: Change the autogenerated stub
   }

   public function reset_password($id)
   {
      try {
         $user             = User::find($id);
         $user->password   = Hash::make($user->document);
         if ($user->save()) {
            $this->emit('showAlert', 'alert-success', __('messages.success.update'));
         } else {
            $this->emit('showAlert', 'alert-error', __('messages.errors.update'));
         }
      } catch (QueryException $exception) {
         $this->emit('showAlert', 'alert-error', __('messages.error.update'));
      }
   }

   public function edit($id)
   {
      $this->emit('edit', $id);
   }
}